name: Build and Release Plugin

on:
  push:
    branches: [ main, master ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: Build plugin
      run: go build -buildmode=plugin -o dummy.so .

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: dummy-plugin
        path: dummy.so

    - name: Upload release asset
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: dummy.so
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}