name: Build and Release Plugin

on:
  push:
    branches: [ main, master ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable
    - name: Build plugin
      id: build
      run: |
        if [ "${{ github.event_name }}" = "release" ]; then
          VERSION="${{ github.ref_name }}"
          OUTPUT="plugin.so"
          LDFLAGS="-X github.com/contre95/soulsolid-dummy-plugin/dummy.Version=$VERSION"
        else
          OUTPUT="dummy.so"
          LDFLAGS=""
        fi
        go build -buildmode=plugin -ldflags "$LDFLAGS" -o "$OUTPUT" .
        echo "output_file=$OUTPUT" >> $GITHUB_OUTPUT
    - name: Upload release asset
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ steps.build.outputs.output_file }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
